### ISSUE TITLE
net6.0版本 上传插件失败

### ISSUE THREAD

**Issue by Jinsheng-Peng** [yiyungent/PluginCore#25]
![image](https://user-images.githubusercontent.com/16498476/196895164-c6e41811-6836-4ea8-b3df-da8ae7c44d5d.png)

主程序和插件项目都是net6.0版本

1、主程序按文档安装后直接运行；
2、插件使用的是命令行模板新建项目，然后把netstander2.0改成net6.0，生成文件 打包为zip
3、打包上传就出现错误了

**Comment by yiyungent** [comment]
zip点开第一级有info.json吗？别打包错了，仔细看下手动文档，

https://moeci.com/PluginCore/zh/PluginDev/Guide/#%E6%96%B9%E5%BC%8F2-%E6%89%8B%E5%8A%A8%E5%88%9B%E5%BB%BA%E6%8F%92%E4%BB%B6%E9%A1%B9%E7%9B%AE

这里有个在线demo，可以随便折腾，用户名密码就是上面默认的，

https://qqbothub.onrender.com/plugincore/admin/index.html#/plugins/list
