### ISSUE TITLE
上传插件后，插件中的API正常，主程序swagger 异常，无法处理插件中的api

### ISSUE THREAD

**Issue by sunnyboyi** [yiyungent/PluginCore#37]
加载HelloWorldPlugin插件后：https://localhost:44354/swagger/v1/swagger.json
报错：SwaggerGeneratorException: Ambiguous HTTP method for action - HelloWorldPlugin.Controllers.HomeController.Get (HelloWorldPlugin). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0

**Comment by yiyungent** [comment]
检查插件action中是否缺少httpmethod，然后重新打包插件，重新启动

**Comment by sunnyboyi** [comment]
重新测试了下  可以了   谢谢
